### ISSUE TITLE
Readme info / Grid

### ISSUE THREAD

**Issue by areski** [mikeorr/WebHelpers2#22]
It would be nice if the Readme explain the difference betwenn WebHelpers2 and WebHelpers1.3 (https://bitbucket.org/bbangert/webhelpers)

Also I see that grid.py is missing from the original webhelpers(https://bitbucket.org/bbangert/webhelpers/src/9ad434bec9a1/webhelpers/html/?at=trunk), this might make migrating to webhelpers2 harder, any plan to add it?

**Comment by mikeorr** [comment]
See http://webhelpers2.readthedocs.org/en/latest/migrate.html for the migration docs and the grid replacement ('webhelpers2_grid' on PyPI).

Added a note in README.txt and in the PyPI entry.

**Comment by areski** [comment]
Thanks!
